name: linting

on: [push, pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: psf/black@stable
        with:
          options: "--check --verbose --color"

      - uses: programmingwithalex/pylinters@v1.4.2
        with:
          skip-mypy: true
          skip-isort: true
