name: linting

on: [pull_request]

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: psf/black@stable
        with:
          options: "--check --verbose --color"

  pylinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: programmingwithalex/pylinters@v1.4.2
        with:
          skip-isort: true
